# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCheck < Formula
  desc "Check Kubernetes resource"
  homepage "https://github.com/Ladicle/kubectl-check"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.1/kubectl-check_darwin-amd64.tar.gz"
    sha256 "712b164c9809921c84860eb29d4aab8498615a15770db4b8ebab34d4eb81ae17"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.1/kubectl-check_linux-amd64.tar.gz"
      sha256 "a1249195ca632d6d83a17c7e5b71e397e40e00301824fdfd038cb1ea2f0ad7d4"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.1/kubectl-check_linux-arm64.tar.gz"
        sha256 "d680257e6888960d85919bc30cea629b8df9c6682faff03c7fac031738125196"
      else
      end
    end
  end

  def install
    bin.install "kubectl-check"
  end
end
