# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCheck < Formula
  desc "Check Kubernetes resource"
  homepage "https://github.com/Ladicle/kubectl-check"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.0/kubectl-check_darwin-amd64.tar.gz"
    sha256 "b7a6a6ef33c0d308e14f71fac1ccee8aad7b4885f21d8b41b8369cdba3d20adf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.0/kubectl-check_linux-amd64.tar.gz"
      sha256 "d88fc12dc21e7d6fa33590a562d97f20e5e9046e38de0b60fbdf8e0809f6bd8f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.0/kubectl-check_linux-arm64.tar.gz"
        sha256 "af1106e6cc3f369bf8401be5ba68a6b32674de5c5eb40037522d3ace66cd4c71"
      else
      end
    end
  end

  def install
    bin.install "kubectl-check"
  end
end
