# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCheck < Formula
  desc "Check Kubernetes resource"
  homepage "https://github.com/Ladicle/kubectl-check"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.1/kubectl-check_darwin-amd64.tar.gz"
    sha256 "2a3d5107b745e60d3ae54b5cf7e4de18eac7c3f3197fbbe2a0a46164a4ff6968"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.1/kubectl-check_linux-amd64.tar.gz"
      sha256 "80419f155a339b54ec7a40acf0927e416e85bbd121d832f3e015b8bbbae87129"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/kubectl-check/releases/download/v1.1.1/kubectl-check_linux-arm64.tar.gz"
        sha256 "b798a1bcbc13ab93a48bd22d7fc88e4b3743dfa1be900b5fcc4cdce8a59db08c"
      else
      end
    end
  end

  def install
    bin.install "kubectl-check"
  end
end
