# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDiagnose < Formula
  desc "Diagnose Kubernetes resource"
  homepage "https://github.com/Ladicle/kubectl-diagnose"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ladicle/kubectl-diagnose/releases/download/v1.0.0/kubectl-diagnose_darwin-amd64.tar.gz"
    sha256 "cc8e33ab4a7f3431b40f194ab83d518e651c38b5b42c7ca358caee97eec7105a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-diagnose/releases/download/v1.0.0/kubectl-diagnose_linux-amd64.tar.gz"
      sha256 "75c4da31c33dbafe6c11868b22b7efa33620bdb9defebd605c6b8fa51cba0a44"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/kubectl-diagnose/releases/download/v1.0.0/kubectl-diagnose_linux-arm64.tar.gz"
        sha256 "9ff096109906f75b4c3a404ffe8d683c469637aba6bedafe8e92630ee8b71043"
      else
      end
    end
  end

  def install
    bin.install "kubectl-diagnose"
  end
end
