# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDiagnose < Formula
  desc "Diagnose Kubernetes resource"
  homepage "https://github.com/Ladicle/kubectl-diagnose"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Ladicle/kubectl-diagnose/releases/download/v1.0.1/kubectl-diagnose_darwin-amd64.tar.gz"
    sha256 "cbf1607d2ce6e732228f74e4ec4c3f2172ad5566acc1977d7a79a5d70b874b8d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-diagnose/releases/download/v1.0.1/kubectl-diagnose_linux-amd64.tar.gz"
      sha256 "f7a036ffc382ad59f84ba5f189514ef71e09f328fce990f92e817434ec12b490"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/kubectl-diagnose/releases/download/v1.0.1/kubectl-diagnose_linux-arm64.tar.gz"
        sha256 "bda324e72a3f938290c6690ebae86c0368066b486b70d4d67e6cb7a49831eb97"
      else
      end
    end
  end

  def install
    bin.install "kubectl-diagnose"
  end
end
